type Catalogue = Readonly<Record<string, string>>;

/**
 * UConn course code -> catalogue title, e.g. `NRE 1000E` -> `Environmental Science`.
 *
 * Generated by `npm run course-map` from UConn's public class search. It is a
 * snapshot, not a live lookup: course numbers and titles change slowly, and a
 * stale entry can only ever produce a suggestion the user can override.
 *
 * It is 255 KB of JSON (62 KB compressed) and only an imported Blackboard feed
 * needs it, so it is not part of the page's own code: `loadCourseCatalogue()`
 * fetches it as a separate file, and until that has finished every lookup finds
 * nothing — which is what a lookup that finds no match already means.
 */
let catalogue: Catalogue | null = null;
let loading: Promise<void> | null = null;

/** Fetches the catalogue once. Resolves when it can be searched; rejects if it could not be fetched. */
export function loadCourseCatalogue(): Promise<void> {
  if (catalogue) return Promise.resolve();
  // The attribute is required: the test runner uses Node's own ESM loader,
  // which refuses a JSON module without it.
  loading ??= import("./ucc-courses.json", { with: { type: "json" } }).then(
    (loaded) => {
      catalogue = loaded.default;
    },
    (error: unknown) => {
      // Offline on the first visit: allow the next attempt to try again.
      loading = null;
      throw error;
    },
  );
  return loading;
}

export function isCourseCatalogueLoaded(): boolean {
  return catalogue !== null;
}

/** The whole catalogue, empty until it has loaded. */
export function courseCatalogue(): Catalogue {
  return catalogue ?? {};
}

let titlesToCodes: Map<string, string[]> | null = null;

function index(): Map<string, string[]> {
  if (titlesToCodes && catalogue) return titlesToCodes;

  const built = new Map<string, string[]>();
  for (const [code, title] of Object.entries(courseCatalogue())) {
    const key = title.trim().toLowerCase();
    if (!key) continue;
    const existing = built.get(key);
    if (existing) existing.push(code);
    else built.set(key, [code]);
  }

  // An empty index built before the catalogue arrived must not stick.
  if (catalogue) titlesToCodes = built;
  return built;
}

/**
 * The course code for a title, when exactly one course owns that title.
 *
 * Blackboard names a class meeting after its catalogue title and gives no code,
 * which is why this exists. It returns `null` rather than guessing when two or
 * more courses share a title — cross-listed courses do that constantly
 * ("Asian Theatre and Performance" is both AAAS 2136 and DRAM 2136) — and the
 * user's own label always wins over anything found here.
 */
export function courseCodeForTitle(title: string | null | undefined): string | null {
  const key = (title ?? "").trim().toLowerCase();
  if (!key) return null;

  const codes = index().get(key);
  return codes && codes.length === 1 ? codes[0] : null;
}

/** Every code that maps to this title, for showing an ambiguous match. */
export function courseCodesForTitle(title: string | null | undefined): string[] {
  const key = (title ?? "").trim().toLowerCase();
  if (!key) return [];
  return index().get(key) ?? [];
}

/** The catalogue title for a code, for labelling a course the user typed. */
export function catalogueTitleForCode(code: string | null | undefined): string | null {
  const key = (code ?? "").replace(/\s+/g, " ").trim().toUpperCase();
  if (!key) return null;
  return courseCatalogue()[key] ?? null;
}
