// The attribute is required: the test runner uses Node's own ESM loader, which
// refuses a JSON module without it.
import courseCodes from "./ucc-courses.json" with { type: "json" };

/**
 * UConn course code -> catalogue title, e.g. `NRE 1000E` -> `Environmental Science`.
 *
 * Generated by `npm run course-map` from UConn's public class search. It is a
 * snapshot, not a live lookup: course numbers and titles change slowly, and a
 * stale entry can only ever produce a suggestion the user can override.
 */
export const COURSE_CATALOGUE: Readonly<Record<string, string>> = courseCodes;

let titlesToCodes: Map<string, string[]> | null = null;

function index(): Map<string, string[]> {
  if (titlesToCodes) return titlesToCodes;

  const built = new Map<string, string[]>();
  for (const [code, title] of Object.entries(COURSE_CATALOGUE)) {
    const key = title.trim().toLowerCase();
    if (!key) continue;
    const existing = built.get(key);
    if (existing) existing.push(code);
    else built.set(key, [code]);
  }

  titlesToCodes = built;
  return built;
}

/**
 * The course code for a title, when exactly one course owns that title.
 *
 * Blackboard names a class meeting after its catalogue title and gives no code,
 * which is why this exists. It returns `null` rather than guessing when two or
 * more courses share a title — cross-listed courses do that constantly
 * ("Asian Theatre and Performance" is both AAAS 2136 and DRAM 2136) — and the
 * user's own label always wins over anything found here.
 */
export function courseCodeForTitle(title: string | null | undefined): string | null {
  const key = (title ?? "").trim().toLowerCase();
  if (!key) return null;

  const codes = index().get(key);
  return codes && codes.length === 1 ? codes[0] : null;
}

/** Every code that maps to this title, for showing an ambiguous match. */
export function courseCodesForTitle(title: string | null | undefined): string[] {
  const key = (title ?? "").trim().toLowerCase();
  if (!key) return [];
  return index().get(key) ?? [];
}

/** The catalogue title for a code, for labelling a course the user typed. */
export function catalogueTitleForCode(code: string | null | undefined): string | null {
  const key = (code ?? "").replace(/\s+/g, " ").trim().toUpperCase();
  if (!key) return null;
  return COURSE_CATALOGUE[key] ?? null;
}
